FROM microsoft/dotnet:1.1.6-runtime
WORKDIR /app
COPY . .

WORKDIR /app/runtime

ENV ASPNETCORE_URLS http://+:9000
ENV ASPNETCORE_ENVIRONMENT Production

EXPOSE 9000

ENTRYPOINT ["dotnet", "api.dll"]

