#!/bin/bash

DOCKER_IMAGE=tutum/mongodb
DOCKER_NAME=mongodb
PORT=27017
STORE_PATH=~/docker/mongodata # local path
STORE_CONTAINER=mongodata
MOUNT_PATH=/data/db

fn_create_docker_database()
{		
if $MACOSX; then
	# Unable to mount only ext4 for docker. So cannot mount MacOSX directory directly
	# Instead, create an empty docker container called mssqldata & then mount the volume
	# there for persistency
	# https://github.com/Microsoft/mssql-docker/issues/7#issuecomment-270840760
	docker create -v /var/opt/$STORE_CONTAINER --name $STORE_CONTAINER $DOCKER_IMAGE

	docker run -d \
    --volumes-from $STORE_CONTAINER \
    --env MYSQL_ROOT_PASSWORD=$PASSWORD \
    --env MYSQL_USER=$USERID \
    --env MYSQL_PASSWORD=$PASSWORD \
    --env MYSQL_DATABASE=$DATABASE_NAME \
    --publish $VMHOST_IP:$PORT \
    --name $DOCKER_NAME \
    $DOCKER_IMAGE 
else

    # MONGODB_PASS - admin account
    # MONGODB_DATABASE - specific database
    # MONGODB_USER - specific user
    # MONGODB_PASS - specific user

    docker run -d \
    --volume $STORE_PATH:$MOUNT_PATH \
    --env MONGODB_PASS=$PASSWORD \
    --env MONGODB_USER=$USERID \
    --env MONGODB_PASSWORD=$PASSWORD \
    --env MONGODB_DATABASE=$DATABASE_NAME \
    --publish $VMHOST_IP:$PORT \
    --name $DOCKER_NAME \
	 $DOCKER_IMAGE 
fi  
}


fn_execute_sql_init() 
{

echo 

}
