#!/bin/bash

DOCKER_IMAGE=mysql:5.7
DOCKER_NAME=mysqldb
PORT=3306
STORE=~/docker/mysqldata
STORE_CONTAINER=mysqldata
MOUNT_PATH=/var/lib/mysql

fn_create_docker_database()
{		
if $MACOSX; then
	# Unable to mount only ext4 for docker. So cannot mount MacOSX directory directly
	# Instead, create an empty docker container called mssqldata & then mount the volume
	# there for persistency
	# https://github.com/Microsoft/mssql-docker/issues/7#issuecomment-270840760
	docker create -v /var/opt/$STORE_CONTAINER --name $STORE_CONTAINER $DOCKER_IMAGE

	docker run -d \
	 --volumes-from $STORE_CONTAINER \
   --env MYSQL_ROOT_PASSWORD=$PASSWORD \
   --env MYSQL_USER=$USERID \
   --env MYSQL_PASSWORD=$PASSWORD \
   --env MYSQL_DATABASE=$DATABASE_NAME \
	 --publish $VMHOST_IP:$PORT \
	 --name $DOCKER_NAME \
	 $DOCKER_IMAGE 
else

	docker run -d \
	 --volume $STORE:$MOUNT_PATH \
   --env MYSQL_ROOT_PASSWORD=$PASSWORD \
   --env MYSQL_USER=$USERID \
   --env MYSQL_PASSWORD=$PASSWORD \
   --env MYSQL_DATABASE=$DATABASE_NAME \
	 --publish $VMHOST_IP:$PORT \
	 --name $DOCKER_NAME \
	 $DOCKER_IMAGE 
fi  
}

fn_execute_sql_init() 
{

echo 

}