#!/bin/bash

DOCKER_IMAGE=postgres:9.6
DOCKER_NAME=pgsqldb
PORT=5432
STORE=~/docker/pgsqldata
STORE_CONTAINER=pgsqldata
MOUNT_PATH=/var/lib/postgresql/data

fn_create_docker_database()
{		
if $MACOSX; then
	# Unable to mount only ext4 for docker. So cannot mount MacOSX directory directly
	# Instead, create an empty docker container called mssqldata & then mount the volume
	# there for persistency
	# https://github.com/Microsoft/mssql-docker/issues/7#issuecomment-270840760
	docker create -v /var/opt/$STORE_CONTAINER --name $STORE_CONTAINER $DOCKER_IMAGE

	docker run -d \
	 --volumes-from $STORE_CONTAINER \
   --env POSTGRES_USER=$USERID \
	 --env POSTGRES_PASSWORD=$PASSWORD \
   --env POSTGRES_DB=$DATABASE_NAME \
	 --publish $VMHOST_IP:$PORT \
	 --name $DOCKER_NAME \
	 $DOCKER_IMAGE 
else

	docker run -d \
	 --volume $STORE:$MOUNT_PATH \
   --env POSTGRES_USER=$USERID \
	 --env POSTGRES_PASSWORD=$PASSWORD \
   --env POSTGRES_DB=$DATABASE_NAME \
	 --publish $VMHOST_IP:$PORT \
	 --name $DOCKER_NAME \
	 $DOCKER_IMAGE 
fi  
}

fn_execute_sql_init() 
{

echo 

}