#!/bin/bash

# Purge the any old dist in the host
rm -rf dist 

# Create a build:image
docker build --rm -t build:image -f Dockerfile.build .

# As you cannot copy directly from the image back to the host
# So, create a container from the image. Then copy the files back to the host.

# Create a web-container (webc) from the web:image
docker create --name webc build:image
docker cp webc:/dist ./dist
chown -R jave:jave ./dist

# Clean up
docker stop webc
docker rm webc
docker rmi build:image

