FROM microsoft/dotnet:1.1.6-sdk-1.1.7

WORKDIR /app
COPY . . 

RUN dotnet restore
RUN dotnet publish -c release -o /dist/release/runtime

# Copy the docker runtime configs
RUN cp configs/docker/* /dist/release/

